version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: register-users
      MYSQL_USER: netdeal
      MYSQL_PASSWORD: teste123
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    image: nginx:1.13
    volumes:
      - ./user-register-front:/usr/share/nginx/html/
    ports:
      - 80:80
      
volumes:
  mysql_data: