server:
 port: 8080

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/register-users
  username: netdeal
  password: teste123
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  generate-ddl: false
  show-sql: false
  hibernate.ddl-auto: none
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
